# .github/workflows/build-windows.yml

name: Build Zed for Windows

# Trigger the workflow manually
on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Test on Windows
    runs-on: windows-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Cache Cargo Registry and Build Dependencies
      - name: Cache Cargo Registry
        uses: actions/cache@v3
        with:
          path: |
            C:\Users\runneradmin\.cargo\registry
            C:\Users\runneradmin\.cargo\git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      # 3. Set up Rust toolchain
      - name: Set Up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      # 4. Update Rust to the latest version
      - name: Update Rust
        run: rustup update

      # 5. Add the wasm32-wasip1 target
      - name: Add wasm32-wasip1 Target
        run: rustup target add wasm32-wasip1

      # 6. Install CMake using Chocolatey
      - name: Install CMake
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --yes
        shell: powershell

      # 7. Verify installations (optional but recommended)
      - name: Verify Rust Installation
        run: rustc --version && cargo --version

      - name: Verify CMake Installation
        run: cmake --version

      # 8. Build the project in Release mode
      - name: Build Zed (Release)
        run: cargo build --release
        shell: bash

      # 9. Run the test suite
      # - name: Run Tests
      #   run: cargo test --release --workspace
      #   shell: bash

      # 10. Upload build artifacts (e.g., binaries, logs)
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: zed-release-build
          path: |
            target/release/
            # Add other paths if needed, e.g., logs or specific binaries

      # 11. (Optional) Set environment variables for troubleshooting
      # - name: Set Environment Variables
      #   run: |
      #     echo "RUST_BACKTRACE=1" >> $GITHUB_ENV
      #     echo "ZED_RC_TOOLKIT_PATH=C:\\Program Files (x86)\\Windows Kits\\10\\bin\\<SDK_version>\\x64" >> $GITHUB_ENV
      #   shell: bash
